spring.application.name=jproject
server.port=8080

spring.datasource.url=jdbc:h2:mem:DB_PRODUCTS
#spring.datasource.driverClassName=org.h2.driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.username=iguzman
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# JWT Configuration
jwt.secret=passwordparatesteo123!
jwt.expirationMs=86400000