###
@baseUrl = http://localhost:2264
@userCredentials = odette:garu
@adminCredentials = admin:admin123
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbnRvbmlvIiwiaWF0IjoxNzQ3OTczNDg4LCJleHAiOjE3NDgwNTk4ODh9.3RIhtu7n_hVcaEcJ9CFCN_5HjtCXRr9YnqsPFfl6ZNU

###
GET {{baseUrl}}/api/phones
Authorization: Bearer {{token}}
###
GET http://localhost:2264/api/phones/make/apple
Authorization: Bearer {{token}}
###
GET http://localhost:2264/api/phones/user/1
Authorization: Bearer {{token}}
###
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{"username":"antonio","password":"garu","email":"a@email.com"}
###
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{"username":"antonio","password":"garu"}

###
POST {{baseUrl}}/api/phones
Authorization: Bearer {{token}}
Content-Type: application/json

{"make":"Apple","model":"iPhone 16","cpu":"A15","ram":32,"price":999}
###
POST {{baseUrl}}/api/error
Authorization: Bearer {{token}}
Content-Type: text/plain

This is an API error
###
GET {{baseUrl}}/api/phones/make/samsung
Authorization: Bearer {{token}}
###
DELETE {{baseUrl}}/api/phones/user/2
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/api/phones/7
Authorization: Bearer {{token}}
Content-Type: application/json

{"make":"Samsung","model":"S25","cpu":"E  xynos 9500","ram":32,"price":899}