spring.application.name=proyectofinal

# Configuración de la base de datos H2
spring.datasource.url=jdbc:h2:mem:musicdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de seguridad
jwt.secret=E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Configuración de WebSocket
websocket.endpoint=/ws
websocket.topic.prefix=/topic
